### ISSUE TITLE
Redshift and other data for trigger

### ISSUE THREAD

**Issue by AlexGKim** [desihub/timedomain#43]
Information about the source, including redshift, type, can be useful for selecting targets in desidiff.  Make information from `zbest` available.

**Comment by AlexGKim** [comment]
The information from the file rather than the database.  The database is loaded asynchronously and is not guaranteed to have the needed data when desidiff is run.

**Comment by davidlmoutard** [comment]
I now have some logic that pulls zbest data (Z, ZERR, ZWARN, SPECTYPE) and matches to spectrum on targetID. this is pulled prior to subtraction.

**Comment by AlexGKim** [comment]
@davidlmoutard implemented this
